//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Angular2MVC.DBContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class TblProduct
    {
        public int Id { get; set; }
        public string MaterialCode { get; set; }
        public string Description { get; set; }
        public string Price { get; set; }
        public string UOM { get; set; }
        public string MaterialType { get; set; }
    }
}
